GET http://localhost:3000/productos
###
GET http://localhost:3000/productos/627ff17ccbd053d4587c972a
###
POST http://localhost:3000/productos
Content-Type: application/json

{
    "nombre": "Guitarra 1",
    "precio": 0,
    "marca": "Ibaneasdasdsad",
    "descripcion" :"Descripcion de prueba"
}
###
PUT http://localhost:3000/productos/627ff17ccbd053d4587c972a
Content-Type: application/json

{
    "producto": "627ff17ccbd053d4587c972a",
    "sucursal" : "627ff0a201f95ce107f8f21e",
    "cantidad":"2"
}

###
DELETE  http://localhost:3000/productos/6280225e99f6bffd45c9830c